#!/bin/bash
echo "Enter first number:"
read num1
echo "Enter second number:"
read num2
echo "Select an operation:"
echo "1. Addition"
echo "2. Subtraction"
echo "3. Multiplication"
echo "4. Division"
read choice
case $choice in
  1) result=$(($num1 + $num2))
     echo "Addition: $num1 + $num2 = $result";;
  2) result=$(($num1 - $num2))
     echo "Subtraction: $num1 - $num2 = $result";;
  3) result=$(($num1 * $num2))
     echo "Multiplication: $num1 * $num2 = $result";;
  4) result=$(($num1 / $num2))
     echo "Division: $num1 / $num2 = $result";;
  *) echo "Invalid choice";;
esac
