#!/bin/bash
echo "Enter a number: "
read num

factorial() {
    if [ $1 -le 1 ]; then
        echo 1
    else
        local temp=$(( $1 - 1 ))
        local result=$(factorial $temp)
        echo $(( $result * $1 ))
    fi
}

fact=$(factorial $num)
echo "The factorial of $num is $fact"
