#!/bin/bash
echo "Enter a number or word:"
read input
#store the original input
original=${input}
#reverse the input
reverse=""
for((i=${#input}-1; i>=0; i--))
do
    reverse="${reverse}${input:$i:1}"
done
#check if the original input and reversed input are same
if [ "$original" = "$reverse" ]
then
    echo "The input is a palindrome."
else
    echo "The input is not a palindrome."
fi
